
-- tabela principal que representa qualquer usuário no sistema 
CREATE TABLE Entidade (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- tabela para dados específicos de Pessoa Física (PF)
CREATE TABLE PessoaFisica (
    ID INT PRIMARY KEY,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    SEXO CHAR(1),
    FOREIGN KEY (ID) REFERENCES Entidade(ID)
);

-- tabela para dados específicos de Pessoa Jurídica (PJ)
CREATE TABLE PessoaJuridica (
    ID INT PRIMARY KEY,
    CNPJ VARCHAR(18) UNIQUE NOT NULL,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    NOME_FANTASIA VARCHAR(255),
    CNAE VARCHAR(10),
    NATUREZA_JURIDICA VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES Entidade(ID)
);

-- tabela para documentos de identificação secundários (Passo 2)
CREATE TABLE Identidade (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT NOT NULL,
    TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
    VALOR_DOCUMENTO VARCHAR(100) NOT NULL,
    DATA_EMISSAO DATE,
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela que identifica a Entidade como um Candidato ao programa
CREATE TABLE Candidato (
    ID INT PRIMARY KEY,
    STATUS_AFILIACAO VARCHAR(50) DEFAULT 'AGUARDANDO_VALIDACAO',
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID) REFERENCES Entidade(ID)
);

-- tabela que gerencia o fluxo de afiliação e seus status
CREATE TABLE Afiliacao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CANDIDATO_ID INT UNIQUE NOT NULL,
    DATA_INICIO TIMESTAMP NOT NULL,
    DATA_FIM TIMESTAMP,
    STATUS VARCHAR(50) NOT NULL,
    FOREIGN KEY (CANDIDATO_ID) REFERENCES Candidato(ID)
);


-- tabela conceitual (Localizacao)
CREATE TABLE Localizacao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT UNIQUE NOT NULL,
    DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela para endereços geográficos
CREATE TABLE GEOGRAFICA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(20),
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(10),
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela para contatos telefônicos
CREATE TABLE FONE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT NOT NULL,
    TIPO VARCHAR(50),
    DDD VARCHAR(5),
    NUMERO_COMPLETO VARCHAR(20) NOT NULL,
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela para contatos virtuais (redes sociais, links, etc.)
CREATE TABLE Virtual (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    CONTATO VARCHAR(255) NOT NULL,
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela para formação acadêmica (Passo 4)
CREATE TABLE Formacao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CANDIDATO_ID INT NOT NULL,
    CURSO VARCHAR(255) NOT NULL,
    TIPO VARCHAR(50),
    INSTITUICAO VARCHAR(255),
    FOREIGN KEY (CANDIDATO_ID) REFERENCES Candidato(ID)
);

-- tabela de perfil (Passo 5)
CREATE TABLE Perfil (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CANDIDATO_ID INT UNIQUE NOT NULL,
    DESCRICAO TEXT,
    FOREIGN KEY (CANDIDATO_ID) REFERENCES Candidato(ID)
);

-- tabelas de apoio (Habilidades e Interesses)
CREATE TABLE Habilidade (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Interesse (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) UNIQUE NOT NULL
);

-- tabelas N:M (muitos para muitos) para Perfil
CREATE TABLE Perfil_Habilidade (
    PERFIL_ID INT NOT NULL,
    HABILIDADE_ID INT NOT NULL,
    PRIMARY KEY (PERFIL_ID, HABILIDADE_ID),
    FOREIGN KEY (PERFIL_ID) REFERENCES Perfil(ID),
    FOREIGN KEY (HABILIDADE_ID) REFERENCES Habilidade(ID)
);

CREATE TABLE Perfil_Interesse (
    PERFIL_ID INT NOT NULL,
    INTERESSE_ID INT NOT NULL,
    PRIMARY KEY (PERFIL_ID, INTERESSE_ID),
    FOREIGN KEY (PERFIL_ID) REFERENCES Perfil(ID),
    FOREIGN KEY (INTERESSE_ID) REFERENCES Interesse(ID)
);

-- tabela para registro do Termo de Compromisso (Passo 6)
CREATE TABLE Termo (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CANDIDATO_ID INT UNIQUE NOT NULL,
    DATA_ACEITACAO TIMESTAMP NOT NULL,
    FOREIGN KEY (CANDIDATO_ID) REFERENCES Candidato(ID)
);

-- tabela de validação de email ou outros tokens de segurança
CREATE TABLE Validacao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT NOT NULL,
    TIPO_VALIDACAO VARCHAR(50) NOT NULL,
    CODIGO VARCHAR(255) UNIQUE NOT NULL,
    DATA_EXPIRACAO TIMESTAMP,
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela para gerenciamento de Textos de Termos/Políticas
CREATE TABLE Texto (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    CONTEUDO TEXT NOT NULL,
    VERSAO VARCHAR(20) UNIQUE NOT NULL,
    TIPO VARCHAR(50) 
);

-- tabela que gerencia itens dentro de um Termo (
CREATE TABLE ItemTermo (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEXTO_ID INT NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    ORDEM INT,
    FOREIGN KEY (TEXTO_ID) REFERENCES Texto(ID)
);

-- tabela para links genéricos ou externos 
CREATE TABLE Link (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    URL VARCHAR(500) UNIQUE NOT NULL
);

-- tabela de Elementos/Componentes
CREATE TABLE Elemento (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) UNIQUE NOT NULL,
    VALOR TEXT
);

-- tabela de Consentimento
CREATE TABLE Consentimento (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDADE_ID INT NOT NULL,
    TIPO_CONSENTIMENTO VARCHAR(100) NOT NULL,
    DATA_ACEITE TIMESTAMP NOT NULL,
    FOREIGN KEY (ENTIDADE_ID) REFERENCES Entidade(ID)
);

-- tabela para itens de acesso 
CREATE TABLE ItemAceite (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PERMISSAO VARCHAR(100) UNIQUE NOT NULL
);

-- tabela para templates de mensagens/e-mails
CREATE TABLE Template (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) UNIQUE NOT NULL,
    ASSUNTO_PADRAO VARCHAR(255),
    CORPO_PADRAO TEXT NOT NULL
);